// Copyright 2025-2026 Rick Rutt

unit constants;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

const
  PLAYER_NAME_FORMAT = 'Plyr %d';
  TOURNAMENT_PLAYER_COUNT = 10;
  TOURNAMENT_GRID_PLAYER_COL = 0;
  TOURNAMENT_GRID_PENTE_WIN_COL = TOURNAMENT_GRID_PLAYER_COL + 1;
  TOURNAMENT_GRID_CAPTURE_WIN_COL = TOURNAMENT_GRID_PENTE_WIN_COL + 1;
  TOURNAMENT_GRID_PENTE_LOSS_COL = TOURNAMENT_GRID_CAPTURE_WIN_COL + 1;
  TOURNAMENT_GRID_CAPTURE_LOSS_COL = TOURNAMENT_GRID_PENTE_LOSS_COL + 1;

  GAME_BOARD_SIZE = 9;
  MIN_COL = 0;
  MIN_ROW = 0;
  CENTER_COL = 4;
  CENTER_ROW = 4;
  MAX_COL = GAME_BOARD_SIZE - 1;
  MAX_ROW = GAME_BOARD_SIZE - 1;

  MIN_PATTERN_INDEX = 0;
  MIDDLE_PATTERN_INDEX = 5;
  MAX_PATTERN_INDEX = 10;

  PERCEPTRON_COUNT = 100;
  PERCEPTRON_DENSITY = 3.0;

  MATCH_EMPTY_DENSITY = 0.3;
  MATCH_SELF_DENSITY = 0.3;
  MATCH_OPPONENT_DENSITY = 0.3;

  WINNING_PERCEPTRON_MUTATION_RATE = 0.05;
  LOSING_PERCEPTRON_MUTATION_RATE = 0.1;

  MIN_DIRECTION = 1;
  HALF_DIRECTION = 4;
  MAX_DIRECTION = 8;

  CAPTURE_PIECE_COUNT = 2;
  PENTE_PIECE_COUNT = 5;

  CAPTURE_WIN_COUNT = 5;

  NEGATIVE_INFINITY = -1e99;

  PERCEPTRONS_FILE_NAME = 'Perceptrons.json';

  AUTO_PLAY_MOVE_SLEEP_MILLISECONDS = 100;
  AUTO_PLAY_GAME_SLEEP_MILLISECONDS = 5000;

  PERCEPTRON_WEIGHT_BIAS = 0.75;
  PERCEPTRON_CELL_WEIGHT_BIAS = 0.75;

  PENTE_WEIGHT_INCREASE = 0.5;
  CAPTURE_WEIGHT_INCREASE = 0.5;

  WINNING_USED_WEIGHT_ADJUSTMENT = +0.1;
  LOSING_USED_WEIGHT_ADJUSTMENT = -0.1;

  WINNING_UNUSED_WEIGHT_ADJUSTMENT = +0.05;
  LOSING_UNUSED_WEIGHT_ADJUSTMENT = -0.05;

  MAXIMUM_PERCEPTRON_WEIGHT = 100;

  PATTERN_MATCH_NOISE_RATE = 0.10;

type
  CellContent = (WhitePiece, BlackPiece, EmptyCell, CapturedCell);
  PatternMatchCell = (DoNotCare, MatchEmpty, MatchSelf, MatchOpponent);

implementation

end.

