// Copyright 2025 Rick Rutt

unit constants;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

const
  GAME_BOARD_SIZE = 9;
  MIN_COL = 0;
  MIN_ROW = 0;
  MAX_COL = GAME_BOARD_SIZE - 1;
  MAX_ROW = GAME_BOARD_SIZE - 1;

  MIN_PATTERN_INDEX = 0;
  MIDDLE_PATTERN_INDEX = 5;
  MAX_PATTERN_INDEX = 10;

  PERCEPTRON_COUNT = 100;
  PERCEPTRON_DENSITY = 0.25;
  MATCH_EMPTY_DENSITY = 0.25;
  MATCH_SELF_DENSITY = 0.25;
  MATCH_OPPONENT_DENSITY = 0.25;

  WINNING_PERCEPTRON_MUTATION_RATE = 0.01;
  LOSING_PERCEPTRON_MUTATION_RATE = 0.1;

  MIN_DIRECTION = 1;
  HALF_DIRECTION = 4;
  MAX_DIRECTION = 8;

  CAPTURE_PIECE_COUNT = 2;
  PENTE_PIECE_COUNT = 5;

  CAPTURE_WIN_COUNT = 5;

  NEGATIVE_INFINITY = -1e99;

  PERCEPTRONS_FILE_NAME = 'Perceptrons.json';

  AUTO_PLAY_MOVE_SLEEP_MILLISECONDS = 100;
  AUTO_PLAY_GAME_SLEEP_MILLISECONDS = 5000;

  PENTE_WEIGHT_FACTOR = 1.1;
  CAPTURE_WEIGHT_FACTOR = 1.1;

  WINNING_WEIGHT_FACTOR = 1.05;
  LOSING_WEIGHT_FACTOR = 0.95;

  MAXIMUM_PERCEPTRON_WEIGHT = 1e10;

type
  CellContent = (WhitePiece, BlackPiece, EmptyCell, CapturedCell);
  PatternMatchCell = (DoNotCare, MatchEmpty, MatchSelf, MatchOpponent);

implementation

end.

